import '@jumpalong/logger'
import { objectFilter } from '@jumpalong/shared'
import DefaultUrlStaff from '../src/staff/staffs/globalDiscoveryUser/DefaultUrlStaff'
import { MockCreateId, createTestEventTemplate } from './utils'
import { EventLineFactory } from '../src/eventLine'
import GlobalUrlsStaff from '../src/staff/staffs/globalDiscoveryUser/GlobalUrlsStaff'
import GlobalDiscoveryUserStaff from '../src/staff/staffs/globalDiscoveryUser/GlobalDiscoveryUserStaff'
import sha256 from 'sha256'
import PoolStaff from '../src/staff/staffs/server/PoolStaff'
import { createStaff } from '../src/staff'
import { Pubkey } from '../src/utils/user'

describe('DefaultUrlStaff', () => {
  test('with DefaultUrl', () => {
    expect(
      objectFilter(
        new EventLineFactory().add(DefaultUrlStaff),
        'deep',
        'core',
        'defaultUrls'
      )
    ).toMatchInlineSnapshot(`
      {
        "core": {
          "defaultUrls": Set {
            "wss://no.str.cr",
            "wss://no-str.org",
            "wss://nos.lol",
            "wss://nostr.com.de",
            "wss://relay.mostr.pub",
            "wss://relay.nostr.wirednet.jp",
            "wss://brb.io",
          },
        },
      }
    `)
  })
  test('add', () => {})
})
describe('GlobalUrlsStaff', () => {
  test('', () => {
    let m = vi.fn()

    createTestEventTemplate()
      .add(MockCreateId)
      .add(mod => mod.out().on('emit', m).mod)
      .add(GlobalUrlsStaff)
      .out()
      .fetchGlobalUrls()
    expect(m).toMatchInlineSnapshot(`
      [MockFunction spy] {
        "calls": [
          [
            "add-filters",
            [
              [
                {
                  "kinds": [
                    10002,
                  ],
                  "limit": 200,
                },
              ],
            ],
          ],
          [
            "add-urls",
            [
              Set {
                "wss://no.str.cr",
                "wss://no-str.org",
                "wss://nos.lol",
                "wss://nostr.com.de",
                "wss://relay.mostr.pub",
                "wss://relay.nostr.wirednet.jp",
                "wss://brb.io",
              },
            ],
          ],
          [
            "sub",
            [
              "wss://no.str.cr",
              [
                {
                  "kinds": [
                    10002,
                  ],
                  "limit": 200,
                },
              ],
              "fdw7me5n5j0",
            ],
          ],
          [
            "sub",
            [
              "wss://no-str.org",
              [
                {
                  "kinds": [
                    10002,
                  ],
                  "limit": 200,
                },
              ],
              "fdw7me5n5j1",
            ],
          ],
          [
            "sub",
            [
              "wss://nos.lol",
              [
                {
                  "kinds": [
                    10002,
                  ],
                  "limit": 200,
                },
              ],
              "fdw7me5n5j2",
            ],
          ],
          [
            "sub",
            [
              "wss://nostr.com.de",
              [
                {
                  "kinds": [
                    10002,
                  ],
                  "limit": 200,
                },
              ],
              "fdw7me5n5j3",
            ],
          ],
          [
            "sub",
            [
              "wss://relay.mostr.pub",
              [
                {
                  "kinds": [
                    10002,
                  ],
                  "limit": 200,
                },
              ],
              "fdw7me5n5j4",
            ],
          ],
          [
            "sub",
            [
              "wss://relay.nostr.wirednet.jp",
              [
                {
                  "kinds": [
                    10002,
                  ],
                  "limit": 200,
                },
              ],
              "fdw7me5n5j5",
            ],
          ],
          [
            "sub",
            [
              "wss://brb.io",
              [
                {
                  "kinds": [
                    10002,
                  ],
                  "limit": 200,
                },
              ],
              "fdw7me5n5j6",
            ],
          ],
        ],
        "results": [
          {
            "type": "return",
            "value": undefined,
          },
          {
            "type": "return",
            "value": undefined,
          },
          {
            "type": "return",
            "value": undefined,
          },
          {
            "type": "return",
            "value": undefined,
          },
          {
            "type": "return",
            "value": undefined,
          },
          {
            "type": "return",
            "value": undefined,
          },
          {
            "type": "return",
            "value": undefined,
          },
          {
            "type": "return",
            "value": undefined,
          },
          {
            "type": "return",
            "value": undefined,
          },
        ],
      }
    `)
  })
})
describe('sha256', () => {
  test('sha256', () => {
    expect(sha256('3333')).toMatchInlineSnapshot(
      `"318aee3fed8c9d040d35a7fc1fa776fb31303833aa2de885354ddf3d44d8fb69"`
    )
    expect(sha256('33333')).toMatchInlineSnapshot(
      `"216e683ff0d2d25165b8bb7ba608c9a628ef299924ca49ab981ec7d2fecd6dad"`
    )
  })

  test('pasereInt', () => {
    expect(
      String(parseInt(sha256('33333'), 16) ^ parseInt(sha256('3333'), 16))
    ).toMatchInlineSnapshot(`"0"`)
  })
})
describe('GlobalDiscoveryUserStaff', () => {
  // expect(generatePrivateKey()).toMatchInlineSnapshot()
  test('', () => {
    expect(
      createTestEventTemplate()
        .add(MockCreateId)
        .add(GlobalUrlsStaff)
        .add(mockGlobalUrls())
        .add(GlobalDiscoveryUserStaff)
        .out()
        .autoGlobalDiscoveryUserByPubkey(Pubkey.fromHex(sha256('xx')))
    ).toMatchInlineSnapshot(`
      Set {
        "wss://relay.shitforce.one/",
        "wss://relay.shitforce.one",
        "wss://relay.farscapian.com/",
        "wss://spore.ws",
        "wss://nostr.coinfundit.com",
        "wss://purplerelay.com/",
        "wss://nostr.hifish.org",
        "wss://at.nostrworks.com/",
        "wss://nostr-1.nbo.angani.co/",
        "wss://relay.nostr.band/trusted",
        "wss://relay.damus.io",
        "wss://relay.plebstr.com/",
        "wss://relay.guggero.org/",
        "wss://nostr.1729.cloud/",
        "wss://rss.nos.social",
        "wss://relay.f7z.io",
        "wss://rnostr.onrender.com/",
        "wss://adult.18plus.social",
        "wss://filter.nostr.wine/npub1kade5vf37snr4hv5hgstav6j5ygry6z09kkq0flp47p8cmeuz5zs7zz2an?broadcast=true&global=all",
        "wss://adre.su/",
        "wss://nostr.zoz-serv.org",
        "wss://umbrel.local:4848",
        "wss://deschooling.us/",
        "wss://nostr-relay.wlvs.space",
        "wss://feeds.nostr.band/tony",
        "wss://nostr.milou.lol/",
        "wss://vitor.nostr1.com/",
        "wss://relay.current.fyi/",
        "wss://relay.nostr.wirednet.jp/",
        "wss://nostr.einundzwanzig.space",
        "wss://nostr.portemonero.com/",
        "wss://nostr.zkid.social",
        "wss://purplerelay.com",
        "wss://relay.bitcoinaudible.com",
        "wss://ae.purplerelay.com",
        "wss://nostr.l00p.org",
        "wss://relay.oldcity-bitcoiners.info",
        "wss://filter.nostr.wine/npub14t0y0l2q3axncpupynq0hx43d2a883s77jgc5m7uc924g2q73e8sg69420?broadcast=true",
        "wss://relay.siamstr.com/",
        "wss://nostr-relay.texashedge.xyz/",
        "wss://relay.nostrati.com",
        "wss://orangepiller.org/",
        "wss://relay.0xchat.com",
        "wss://anon.computer",
        "wss://filter.stealth.wine?broadcast=true",
        "wss://nos.win/",
        "wss://relay.nostr.band/all",
        "wss://puravida.nostr.land/",
        "wss://nostr.oxtr.dev/",
        "wss://nostr.bitcoiner.social/",
      }
    `)
  })
})

function mockGlobalUrls() {
  return createStaff(GlobalUrlsStaff, m => {
    m.out().addGlobalUrls(
      new Set([
        'wss://relay.mostr.pub',
        'wss://relay.shitforce.one',
        'wss://nostr.coinfundit.com',
        'wss://nos.lol',
        'wss://relay.damus.io',
        'wss://relay-jp.nostr.wirednet.jp',
        'wss://nostr-relay.nokotaro.com',
        'wss://nostr.holybea.com',
        'wss://nostr.fediverse.jp',
        'wss://yabu.me',
        'wss://nostr.wine/',
        'wss://puravida.nostr.land/',
        'wss://eden.nostr.land/',
        'wss://atlas.nostr.land/',
        'wss://nos.lol/',
        'wss://nostr.mom/',
        'wss://nostr.oxtr.dev/',
        'wss://relay.nostr.bg/',
        'wss://relay.damus.io/',
        'wss://nostr-pub.wellorder.net/',
        'wss://relay.snort.social/',
        'wss://relay.nostr.com.au/',
        'wss://nostr.bitcoiner.social/',
        'wss://filter.nostr.wine/',
        'wss://relay.nostr.band/',
        'wss://relay.nostrati.com/',
        'wss://relay.orangepill.dev/',
        'wss://relay.noswhere.com/',
        'wss://nostr.inosta.cc/',
        'wss://nostr.milou.lol/',
        'wss://feeds.nostr.band/',
        'wss://adult.18plus.social/',
        'wss://relay.n057r.club/',
        'wss://relay.plebstr.com/',
        'wss://relay.nostrplebs.com/',
        'wss://nsrelay.assilvestrar.club/',
        'wss://offchain.pub/',
        'wss://bitcoiner.social/',
        'wss://vitor.nostr1.com/',
        'wss://nostr.wine',
        'wss://nostr-pub.wellorder.net',
        'wss://offchain.pub',
        'wss://nostr.aveygo.dedyn.io',
        'wss://relay.current.fyi/',
        'wss://spore.ws/',
        'wss://relay.0xchat.com/',
        'wss://nostr.zebedee.cloud/',
        'wss://relay.nostr.wirednet.jp/',
        'wss://nostr.zoel.network/',
        'wss://relay.leligobit.link/',
        'wss://relay.nostr.directory/',
        'wss://nostr.600.wtf/',
        'wss://n.ok0.org/',
        'wss://relayable.org/',
        'wss://nostr.hankhub.net/',
        'wss://relay.nostrcn.com/',
        'wss://purplerelay.com/',
        'wss://nostr-02.yakihonne.com/',
        'wss://nostr-02.dorafactory.org/',
        'wss://yabu.me/',
        'wss://relay.blowater.app/',
        'wss://dev.nostrplayground.com/',
        'wss://gan.yestr.day/',
        'wss://relay.service.mapboss.co.th/',
        'wss://relay.mapboss.co.th/',
        'wss://purplepag.es/',
        'wss://relay.mostr.pub/',
        'wss://nostr-01.yakihonne.com/',
        'wss://newperspectives.duckdns.org/',
        'wss://nostr-03.dorafactory.org/',
        'wss://relay.notoshi.win/',
        'wss://nostr.data.haus/',
        'wss://relay.primal.net/',
        'wss://relay.snort.social',
        'wss://nostr.einundzwanzig.space',
        'wss://nostr.fmt.wiz.biz',
        'wss://relay.nostr.wirednet.jp',
        'wss://nostrich.friendship.tw/',
        'wss://relay.nostr.co.kr/',
        'wss://lnbits.aruku.kro.kr/nostrrelay/private',
        'wss://nostr.8777.ch/',
        'wss://slick.mjex.me/',
        'wss://n.wingu.se/',
        'wss://nostr.gerbils.online/',
        'wss://nostr.dvdt.dev/',
        'wss://relay.primal.net',
        'wss://frjosh.nostr1.com',
        'wss://relay.nostr.band',
        'wss://eden.nostr.land',
        'wss://africa.nostr.joburg/',
        'wss://nostr.jcloud.es/',
        'wss://za.purplerelay.com/',
        'wss://nostr.olwe.link/',
        'wss://nostr.notmyhostna.me/',
        'wss://relay.shitforce.one/',
        'wss://nostr.donky.social/',
        'wss://nostr.gleeze.com/',
        'wss://nostrua.com/',
        'wss://relay.despera.space/',
        'wss://relay.ryzizub.com/',
        'wss://nostr.sats.li/',
        'wss://relay.guggero.org/',
        'wss://nostr.thank.eu/',
        'wss://nostr-relay.wlvs.space/',
        'wss://nostr.1729.cloud/',
        'wss://relay.nostrich.de/',
        'wss://nostr.v0l.io/',
        'wss://nostr.fmt.wiz.biz/',
        'wss://pow.nostrati.com/',
        'wss://nostr-2.afarazit.eu/',
        'wss://nostr.btcmp.com/',
        'wss://nostr.localhost.re/',
        'wss://nostr.lol',
        'wss://nostr.mom',
        'wss://relay.nostr.info',
        'wss://strfry.nostr.lighting/',
        'wss://nostr.portemonero.com/',
        'wss://nostr2.kleofash.eu/',
        'wss://nostr.cheeserobot.org/',
        'wss://btc.klendazu.com/',
        'wss://nostr.kaosfield.net/',
        'ws://relay.nostr.wirednet.jp/',
        'wss://relay.nostr.moctane.com/',
        'wss://directory.yabu.me/',
        'wss://relay.geyser.fund',
        'wss://purplepag.es',
        'wss://relay.hodl.ar/',
        'ws://relay.nostr.bg/',
        'wss://paid.no.str.cr/',
        'wss://nostr.maximacitadel.org/',
        'wss://staging.yabu.me/',
        'wss://nostr.papanode.com/',
        'wss://nostr.lbdev.fun/',
        'wss://mnl.v0l.io/',
        'wss://search.nos.today',
        'wss://damus.relay.center',
        'wss://directory.yabu.me',
        'wss://relay.2nodez.com',
        'wss://relay.nostr.moctane.com',
        'wss://nostr.zkid.social',
        'wss://tmp-relay.cesc.trade',
        'wss://global-relay.cesc.trade',
        'wss://vitor.relaying.io',
        'wss://eden.relay.center',
        'wss://public.relaying.io',
        'wss://purplerelay.com',
        'wss://relay.cxcore.net',
        'wss://annal.purplerelay.com',
        'wss://nostr.easydns.ca',
        'wss://nostr-02.yakihonne.com',
        'wss://nostr.sathoarder.com',
        'wss://n.ok0.org',
        'wss://nrelay.c-stellar.net',
        'wss://relay.nostromo.social',
        'wss://relay-jp.shino3.net',
        'wss://140.f7z.io',
        'wss://relay.siamstr.com',
        'wss://srtrelay.c-stellar.net',
        'wss://nostrue.com',
        'wss://za.purplerelay.com',
        'wss://rss.nos.social',
        'wss://pleb.cloud',
        'wss://booger.pro',
        'wss://relay.bitcoinaudible.com',
        'wss://strfry.kisiel.net.pl',
        'wss://relay.leafbodhi.com',
        'wss://nostr.portemonero.com',
        'wss://xmr.usenostr.org',
        'wss://ae.purplerelay.com',
        'wss://relay.kamp.site',
        'wss://nostr.noones.com',
        'wss://relay.minds.com/nostr/v1/ws',
        'wss://b.rtay.org',
        'wss://relay.wellorder.net',
        'wss://nostr.cercatrova.me',
        'wss://relay.bitcoinbarcelona.xyz',
        'wss://feeds.nostr.band/popular',
        'wss://btc.klendazu.com',
        'wss://relay.stoner.com',
        'wss://nostr.mutinywallet.com',
        'wss://nostr.mining.sc',
        'wss://relay.layer.systems',
        'wss://nostr.filmweb.pl',
        'wss://relay.leesalminen.com',
        'wss://nostr.data.haus',
        'wss://nostr-relay.texashedge.xyz',
        'wss://nostr.thank.eu',
        'wss://relay.nostr.youlot.org',
        'wss://snort.relay.center',
        'wss://nb.relay.center',
        'wss://nostr.gleeze.com',
        'wss://nostr.l00p.org',
        'wss://nostr.nodeofsven.com',
        'wss://relay.pleb.to',
        'wss://nostr.libreleaf.com',
        'wss://nostr-verif.slothy.win',
        'wss://relay.f7z.io',
        'wss://relay.oldcity-bitcoiners.info',
        'wss://relay.casualcrypto.date',
        'wss://filter.stealth.wine/npub134lfcqtw0rwzpey20suye7gjxep2ts6lhqemp7c4zhxe8jsj24wqqzelwh?broadcast=true',
        'wss://relay.corpum.com',
        'wss://cellar.nostr.wine',
        'wss://filter.nostr.wine/npub14t0y0l2q3axncpupynq0hx43d2a883s77jgc5m7uc924g2q73e8sg69420?broadcast=true',
        'wss://sakhalin.nostr1.com',
        'wss://21ideas.nostr1.com',
        'wss://welcome.nostr.wine',
        'wss://th1.nostr.earnkrub.xyz/',
        'wss://teemie1-relay.duckdns.org/',
        'wss://relay.siamstr.com/',
        'wss://relay.satoshidnc.com/',
        'wss://nostr.zenon.info/',
        'wss://nostr.lorentz.is/',
        'wss://relay.calders.us/',
        'wss://relay.nostrhackers.online/',
        'wss://relay.toastr.space/',
        'wss://nostrue.com/',
        'wss://nostr.roundrockbitcoiners.com/',
        'wss://nostr-relay.texashedge.xyz/',
        'wss://nostr.libreleaf.com/',
        'wss://nostr.zbd.gg',
        'wss://arc1.arcadelabs.co/',
        'wss://nostr.bitcoin-21.org/',
        'wss://nostr.zoz-serv.org/',
        'wss://nostr-badur.onrender.com/',
        'wss://la.relayable.org/',
        'wss://jingle.carlos-cdb.top/',
        'wss://rnostr.onrender.com/',
        'wss://nostr.u53.us',
        'wss://nostr21.com/',
        'wss://relay.nostrcheck.me/',
        'wss://relay.nostrss.re/',
        'wss://in.purplerelay.com/',
        'wss://ae.purplerelay.com/',
        'wss://relay.hawties.xyz/',
        'wss://filter.nostr.wine/npub1dqg3at6cmahs4fqlu027lllkm942h90hyvgsuxqqe9pg4p09sn0szs3643?broadcast=true',
        'wss://e43lji2bfyqowymy5k6mpmitw7ntideu5z4l7f6qsiwi44crhraiqpqd.local',
        'wss://nostr.mutinywallet.com/',
        'wss://no.str.cr/',
        'wss://nostr.lnbitcoin.cz/',
        'wss://nostr.swiss-enigma.ch/',
        'wss://relay.example.com/',
        'wss://relay.sovereignengineering.io',
        'wss://relay.nostrcheck.me',
        'wss://nostr.xmr.rocks',
        'wss://soloco.nl',
        'wss://relay.local:4443/',
        'wss://relay.stemstr.app/',
        'wss://nostr.fairshare.social/',
        'wss://nostr.supremestack.xyz/',
        'wss://nostr.coinfundit.com/',
        'wss://relay.dwadziesciajeden.pl/',
        'wss://relay.nostrplebs.com',
        'wss://relay.nostrified.org',
        'wss://nostr.thesamecat.io',
        'wss://adult.18plus.social',
        'wss://nostrelay.yeghro.site',
        'wss://filter.nostr.wine/npub1kade5vf37snr4hv5hgstav6j5ygry6z09kkq0flp47p8cmeuz5zs7zz2an?broadcast=true&global=all',
        'wss://yestr.me',
        'wss://relay.hawties.xyz',
        'wss://private.red.gb.net',
        'wss://relay.yozora.world',
        'wss://filter.nostr.wine/npub1m78s5eqv8l7snc5nnxdvlgue6pt5epgplndtem99quhwyptas7jss2qx53?broadcast=true',
        'wss://nostr.decentony.com',
        'wss://pyramid.fiatjaf.com',
        'wss://us.nostr.land/',
        'wss://localhost:8080/',
        'wss://nostr.cercatrova.me/',
        'wss://btcpay.kukks.org/nostr',
        'wss://btcpay.kukks.org/nostr/ws',
        'wss://kukks.org/nostr',
        'wss://yestr.me/',
        'wss://bitcoinmaximalists.online/',
        'wss://relayable.org',
        'wss://nostr.oxtr.dev',
        'wss://nostr.bitcoiner.social',
        'wss://relay.nostr.bg',
        'wss://freerelay.xyz',
        'wss://relay.current.fyi',
        'wss://nostr21.com',
        'wss://usenostr.org',
        'wss://relay.orangepill.dev',
        'wss://relay.nostr.com.au',
        'wss://relay.noswhere.com',
        'wss://relay.nostrati.com',
        'wss://nostr.inosta.cc',
        'wss://nostr-01.yakihonne.com',
        'wss://nostr-02.dorafactory.org',
        'wss://brb.io/',
        'wss://nostr.orangepill.dev/',
        'wss://saltivka.org',
        'wss://frens.nostr1.com',
        'wss://welcome.nostr.wine/',
        'wss://nostr.cahlen.org/',
        'wss://orangepiller.org/',
        'wss://lnb.bolverker.com/nostrrelay/b07d5967-b20a-4e83-a713-8bbea0694660',
        'wss://adre.su/',
        'wss://nostr.iadenisov.ru/',
        'wss://nostr.0xtr.dev/',
        'wss://feeds.nostr.band/pics',
        'wss://nostr.nodeofsven.com/',
        'wss://nostr.hubmaker.io/',
        'wss://relay.stemstr.app',
        'wss://nostr.notmyhostna.me',
        'wss://nostrich.friendship.tw',
        'wss://nsc.pleb.cloud',
        'wss://v2-connection.nostr-demo.relayaas.com',
        'wss://r.hostr.cc',
        'wss://nostr.blockpower.capital',
        'wss://nostr.zoz-serv.org',
        'wss://nostr.umbrel.karmas.fr',
        'wss://freespeech.casa',
        'wss://filter.stealth.wine/npub18kzz4lkdtc5n729kvfunxuz287uvu9f64ywhjz43ra482t2y5sks0mx5sz?broadcast=true',
        'wss://offchain.relay.center',
        'wss://nostr.simplex.icu',
        'wss://nostr.bongbong.com',
        'wss://rsslay.nostr.moe',
        'wss://dev.nostrplayground.com',
        'wss://relay.nostr.hach.re',
        'wss://relay.0xchat.com',
        'wss://nostr.primz.org',
        'wss://satdow.relaying.io',
        'wss://nostr.heavyrubberslave.com',
        'wss://relay.dwadziesciajeden.pl',
        'wss://nostr.btcmp.com',
        'wss://rsslay.onrender.com',
        'wss://nostr.1f52b.xyz',
        'wss://nostr1.current.fyi',
        'wss://nostr.asdf.mx',
        'wss://nostr-relay.lnmarkets.com',
        'wss://nostr.actn.io',
        'wss://relay.nostrss.re',
        'wss://relay.n057r.club',
        'wss://nostr3.actn.io',
        'wss://nostr.globals.fans',
        'wss://nostr-usa.ka1gbeoa21bnm.us-west-2.cs.amazonlightsail.com',
        'wss://nostr.vulpem.com',
        'wss://relay.nostr.ro',
        'wss://bitcoiner.social',
        'wss://brb.io',
        'wss://relay.nostr.au',
        'wss://nostr-tbd.website',
        'wss://nostr.rocket-tech.net',
        'wss://filter.nostr.wine/npub12ddgadsx8662zp5fp8f9qyn8rh2uxlgllqzkzwztwhyjtl2dglhq9rr2ut?broadcast=true',
        'wss://spore.ws',
        'wss://slick.mjex.me',
        'wss://nostr-badur.onrender.com',
        'wss://au.relayable.org',
        'wss://nostr.strits.dk',
        'wss://la.relayable.org',
        'wss://nostr-verified.wellorder.net',
        'wss://nostr.lu.ke',
        'wss://nostr.bitocial.xyz',
        'wss://relay.lacosanostr.com',
        'wss://relay-pub.deschooling.us',
        'wss://deschooling.us',
        'wss://relay.plebstr.com',
        'wss://nostr.mikedilger.com',
        'wss://nostr.itas.li',
        'wss://relay.badgr.space',
        'wss://relay.bitcoinpark.com',
        'wss://relay.stpaulinternet.net',
        'wss://relay.toastr.space',
        'wss://relay.sendstr.com',
        'wss://nostr.hifish.org',
        'wss://relay.nostrology.org',
        'wss://nostr-relay.app',
        'wss://paid.spore.ws',
        'wss://nostr.kaosfield.net',
        'wss://relay.nostrcn.com',
        'wss://relay.leligobit.link',
        'wss://feeds.nostr.band/nostrhispano',
        'wss://jovial-fuchsia-euhyboma.scarab.im',
        'wss://nostr-1.nbo.angani.co',
        'wss://relay.piazza.today',
        'wss://adre.su',
        'wss://anon.computer',
        'wss://filter.stealth.wine?broadcast=true',
        'wss://filter.stealth.wine/npub12w5rjt5hrdrrym3ap7yk0kchcnmuefx5905hnvtxgyjv3a56755qx6u7fz?broadcast=true&global=all',
        'wss://filter.stealth.wine/npub18kzz4lkdtc5n729kvfunxuz287uvu9f64ywhjz43ra482t2y5sks0mx5sz?broadcast=true&global=all',
        'wss://umbrel.local:4848',
        'wss://nostr.zkid.social/',
        'wss://nos.win/',
        'wss://swiss.nostr.lc/',
        'wss://relay.sovereignengineering.io/',
        'wss://Nostr.wine/',
        'wss://relay.nostrica.com/',
        'wss://relay-jp.nostr.wirednet.jp/',
        'wss://nostr-relay.nokotaro.com/',
        'wss://nostr.holybea.com/',
        'wss://nostr.fediverse.jp/',
        'wss://relay.nostriches.org/',
        'ws://umbrel:4848/',
        'wss://lightningrelay.com/',
        'wss://at.nostrworks.com/',
        'wss://deschooling.us/',
        'wss://knostr.neutrine.com/',
        'wss://nostr-01.bolt.observer/',
        'wss://nostr-1.nbo.angani.co/',
        'wss://relay.wellorder.net/',
        'wss://140.f7z.io/',
        'wss://pyramid.fiatjaf.com/',
        'wss://nostr1.tunnelsats.com',
        'wss://nostr-relay.wlvs.space',
        'wss://relay.stpaulinternet.net/',
        'wss://nostr.fbxl.net/',
        'wss://relay.wavlake.com/',
        'wss://rsslay.nostr.net/',
        'wss://nostr.topeth.info/',
        'wss://creatr.nostr.wine/',
        'wss://inbox.nostr.wine/',
        'wss://relay.sovereign-stack.org/',
        'wss://relay.farscapian.com/',
        'wss://relay.oldcity-bitcoiners.info/',
        'wss://relay-direct.noscription.org/',
        'wss://feeds.nostr.band/tony',
        'wss://nostr.33co.de/',
        'wss://feeds.nostr.band/memes',
        'wss://relay.proxymana.net/',
        'wss://feeds.nostr.band/newstr',
        'wss://relay.nostr.band/trusted',
        'wss://relay.nostr.band/restricted',
        'wss://relay.nostr.band/all',
        'wss://nostr.app.runonflux.io/',
        'wss://nostr.metamadeenah.com/',
        'wss://nostr.lu.ke/',
        'wss://ln.weedstr.net/nostrrelay/weedstr',
        'ws://games.gamertron.net:4848/',
        'wss://nrelay-jp.c-stellar.net/',
        'wss://relay-jp.shino3.net/',
        'wss://r.kojira.io/',
        'wss://srtrelay.c-stellar.net/',
        'wss://relay.magiccity.live/',
        'wss://nostr.bilthon.dev/',
        'wss://nostr.notribe.net/',
        'wss://relay.nostrassets.com/',
        'wss://therelayofallrelays.nostr1.com/',
        'wss://zh.nostr1.com/',
        'wss://sfr0.nostr1.com/',
        'wss://relay.sendstr.com/',
        'wss://relay.nostr.nu/',
        'wss://nostr.vulpem.com/',
        'wss://nostr.dynopool.com',
      ])
    )

    return m
  })
}
